import { library } from '@fortawesome/fontawesome-svg-core'
import {
    faPaperPlane as fasPaperPlane,
    faExclamationCircle as fasExclamationCircle,
    faExclamation as fasExclamation,
    faExclamationTriangle as fasExclamationTriangle,
    faInfoCircle as fasInfoCircle,
    faHashtag as fasHashtag,
    faTag as fasTag,
    faCaretLeft as fasCaretLeft,
    faCaretRight as fasCaretRight,
    faImage as fasImage,
    faLink as fasLink,
    faStar as fasStar,
    faFont as fasFont,
    faThumbsUp as fasThumbsUp,
    faComment as fasComment,
    faShareSquare as fasShareSquare,
    faHeart as fasHeart,
    faRetweet as fasRetweet,
    faCheck as fasCheck,
    faChevronLeft as fasChevronLeft,
    faChevronRight as fasChevronRight,
    faChevronDown as fasChevronDown,
    faChevronUp as fasChevronUp,
	faCaretDown as fasCaretDown,
} from "@fortawesome/pro-solid-svg-icons";

import {
    faChevronLeft as farChevronLeft,
    faChevronRight as farChevronRight,
    faChevronDown as farChevronDown,
    faChevronUp as farChevronUp,
    faSearch as farSearch,
    faCheck as farCheck,
    faCheckCircle as farCheckCircle,
    faTimes as farTimes,
    faSmile as farSmile,
    faEllipsisH as farEllipsisH,
    faUser as farUser,
    faSync as farSync,
    faFilter as farFilter,
    faListAlt as farListAlt,
    faClock as farClock,
    faExclamationCircle as farExclamationCircle,
    faHourglass as farHourglass,
    faRobot as farRobot,
    faPageBreak as farPageBreak,
    faSparkles as farSparkles,
    faFont as farFont,
    faBookmark as farBookmark,
    faPaperPlane as farPaperPlane,
    faLifeRing as farLifeRing,
    faFileAlt as farFileAlt,
    faInfoCircle as farInfoCircle,
    faCalendar as farCalendar,
    faPlus as farPlus,
    faStore as farStore,
    faSignOutAlt as farSignOutAlt,
	faGripLinesVertical as farGripLinesVertical,
	faLink as farLink,
	faAngleLeft as farAngleLeft,
	faAngleRight as farAngleRight,
	faTrashAlt as farTrashAlt,
	faRandom as farRandom,
	faCalendarAlt as farCalendarAlt,
	faEye as farEye,
	faStar as farStar,
} from "@fortawesome/pro-regular-svg-icons";

import {
    faPlus as falPlus,
    faTimes as falTimes,
	faTrashAlt as falTrashAlt,
	faStar as falStar,
	faTag as falTag,
	faLink as falLink,
	faImage as falImage,
	faVideo as falVideo,
	faText as falText,
	faFont as falFont

} from "@fortawesome/pro-light-svg-icons";
import { 
	faFacebookF as fabFacebookF, 
	faTwitter as fabTwitter, 
	faFacebookSquare as fabFacebookSquare, 
	faTwitterSquare  as fabTwitterSquare, 
	faInstagram  as fabInstagram, 
	faInstagramSquare as fabInstagramSquare,
} from "@fortawesome/free-brands-svg-icons";

var iconSolid = [
	fasPaperPlane,
    fasExclamationCircle,
    fasExclamation,
    fasExclamationTriangle,
    fasInfoCircle,
    fasHashtag,
    fasTag,
    fasCaretLeft,
    fasCaretRight,
    fasImage,
    fasLink,
    fasStar,
    fasFont,
    fasThumbsUp,
    fasComment,
    fasShareSquare,
    fasHeart,
    fasRetweet,
    fasCheck,
    fasChevronLeft,
    fasChevronRight,
    fasChevronDown,
    fasChevronUp,
    fasCaretDown,
]
var regularIcons = [
	farChevronLeft,
    farChevronRight,
    farChevronDown,
    farChevronUp,
    farSearch,
    farCheck,
    farCheckCircle,
    farTimes,
    farSmile,
    farEllipsisH,
    farUser,
    farSync,
    farFilter,
    farListAlt,
    farClock,
    farExclamationCircle,
    farHourglass,
    farRobot,
    farPageBreak,
    farSparkles,
    farFont,
    farBookmark,
    farPaperPlane,
    farLifeRing,
    farFileAlt,
    farInfoCircle,
    farCalendar,
    farPlus,
    farStore,
    farSignOutAlt,
	farGripLinesVertical,
	farLink,
	farAngleLeft,
	farAngleRight,
	farTrashAlt,
	farRandom,
	farCalendarAlt,
	farEye,
	farStar
]
var lightIcons = [
	falPlus,
	falTimes,
	falTrashAlt,
	falStar,
	falTag,
	falLink,
	falImage,
	falVideo,
	falText,
	falFont
]
var brandIcons = [
	fabFacebookF, 
	fabTwitter, 
	fabFacebookSquare, 
	fabTwitterSquare, 
	fabInstagram, 
	fabInstagramSquare,
]
var icons = [
	...iconSolid,
	...regularIcons,
	...lightIcons,
	...brandIcons
]
for (let index = 0; index < icons.length; index++) {
    library.add(icons[index])
}